from src.workflows.graph_builder import BuildGraph
from langchain_core.messages import SystemMessage
from config.logging_config import *  # Ensures logging is configured once
import logging
logger = logging.getLogger(__name__)  # __name__ will show module/class context


if __name__ == '__main__':
    logger.info("main execution start")

    user_messages = ["Tell me how GenAI is used in healthcare.",
                     "Tell me latest information about Dr. APJ Abdul Kalam from web world?",
                     "Do you think India will be able to develop there own LLM? Agentic AI is fascinating!"]

    for message in user_messages:
        state = {'messages': [SystemMessage(content=f"{message}")], 'last_route': '', 'retry_count': 0}

        # Build and compile the graph
        app = BuildGraph(state).build_graph()

        # Run the stateful agent
        output = app.stream(state)

        for event in output:
            print(event)


#################  SAMPLE RUN LOG #######################
"""
E:\Learning\Agentic_AI_V2_Projects\agentic-RAG-with-supervisor-node\venv\python.exe E:\Learning\Agentic_AI_V2_Projects\agentic-RAG-with-supervisor-node\main.py 
[SupervisorNode.classify_request]:START: {'messages': [SystemMessage(content='Tell me how GenAI is used in healthcare.', additional_kwargs={}, response_metadata={})], 'last_route': '', 'retry_count': 0}
[SupervisorNode.classify_request]:END: {'messages': [SystemMessage(content='rag', additional_kwargs={}, response_metadata={})], 'validation_passed': '', 'last_route': 'rag', 'retry_count': 0}
[SupervisorNode.get_route]:START: {'messages': [SystemMessage(content='Tell me how GenAI is used in healthcare.', additional_kwargs={}, response_metadata={}), SystemMessage(content='rag', additional_kwargs={}, response_metadata={})], 'validation_passed': '', 'last_route': 'rag', 'retry_count': 0}
next_node: rag
[SupervisorNode.get_route]:END: {'messages': [SystemMessage(content='Tell me how GenAI is used in healthcare.', additional_kwargs={}, response_metadata={}), SystemMessage(content='rag', additional_kwargs={}, response_metadata={})], 'validation_passed': '', 'last_route': 'rag', 'retry_count': 0}
{'supervisor': {'messages': [SystemMessage(content='rag', additional_kwargs={}, response_metadata={})], 'validation_passed': '', 'last_route': 'rag', 'retry_count': 0}}
{'rag': {'messages': [SystemMessage(content="The provided text mentions generative AI's use across multiple domains, including healthcare, but doesn't offer specifics on how it's used in that sector.", additional_kwargs={}, response_metadata={})], 'validation_passed': False, 'last_route': 'rag', 'retry_count': 0}}
[ValidationNode.validation_router]: START: {'messages': [SystemMessage(content='Tell me how GenAI is used in healthcare.', additional_kwargs={}, response_metadata={}), SystemMessage(content='rag', additional_kwargs={}, response_metadata={}), SystemMessage(content="The provided text mentions generative AI's use across multiple domains, including healthcare, but doesn't offer specifics on how it's used in that sector.", additional_kwargs={}, response_metadata={})], 'validation_passed': False, 'last_route': 'rag', 'retry_count': 0}
[ValidationNode.validation_router]: validation_passed=True, retry_count=0
{'validation_router': {'messages': [SystemMessage(content='Tell me how GenAI is used in healthcare.', additional_kwargs={}, response_metadata={}), SystemMessage(content='rag', additional_kwargs={}, response_metadata={}), SystemMessage(content="The provided text mentions generative AI's use across multiple domains, including healthcare, but doesn't offer specifics on how it's used in that sector.", additional_kwargs={}, response_metadata={})], 'validation_passed': True, 'last_route': 'rag', 'retry_count': 0}}


[SupervisorNode.classify_request]:START: {'messages': [SystemMessage(content='Tell me latest information about Dr. APJ Abdul Kalam from web world?', additional_kwargs={}, response_metadata={})], 'last_route': '', 'retry_count': 0}
[SupervisorNode.classify_request]:END: {'messages': [SystemMessage(content='web', additional_kwargs={}, response_metadata={})], 'validation_passed': '', 'last_route': 'web', 'retry_count': 0}
[SupervisorNode.get_route]:START: {'messages': [SystemMessage(content='Tell me latest information about Dr. APJ Abdul Kalam from web world?', additional_kwargs={}, response_metadata={}), SystemMessage(content='web', additional_kwargs={}, response_metadata={})], 'validation_passed': '', 'last_route': 'web', 'retry_count': 0}
next_node: web
[SupervisorNode.get_route]:END: {'messages': [SystemMessage(content='Tell me latest information about Dr. APJ Abdul Kalam from web world?', additional_kwargs={}, response_metadata={}), SystemMessage(content='web', additional_kwargs={}, response_metadata={})], 'validation_passed': '', 'last_route': 'web', 'retry_count': 0}
{'supervisor': {'messages': [SystemMessage(content='web', additional_kwargs={}, response_metadata={})], 'validation_passed': '', 'last_route': 'web', 'retry_count': 0}}
{'web': {'messages': [SystemMessage(content='Dr. Avul Pakir Jainulabdeen (APJ) Abdul Kalam, fondly known as the "Missile Man of India," was one of India\'s most esteemed scientists and statesmen. Born on October 15, 1931, in Rameswaram, Tamil Nadu, Kalam came from a humble background. A.P.J. Abdul Kalam, the esteemed scientist and former president of India, left an enduring legacy through his contributions to space research and inspired millions with his vision for a prosperous country. A grand tribute to one of India\'s most loved and respected figures is officially in the making. At the 78th Cannes Film Festival, the makers of Kalam: The Missile Man of India announced a biopic based on the life of Bharat Ratna Dr APJ Abdul Kalam. Known for his incredible contributions to India\'s space and missile programmes, and his time as the 11th President of India, Dr Kalam is a ... APJ Abdul Kalam Death Anniversary: Fondly called India\'s \'Missile man\', Dr Kalam was particularly close to young people and he loved to be among students. The great passion for science that drove Dr. APJ Abdul Kalam\'s innovative efforts in missile and aerospace technologies gained him the moniker "Missile Man of India." His commitment to scientific advancement till now inspires great number of young people to seek jobs in science and technology.', additional_kwargs={}, response_metadata={})], 'validation_passed': False, 'last_route': 'web', 'retry_count': 0}}
[ValidationNode.validation_router]: START: {'messages': [SystemMessage(content='Tell me latest information about Dr. APJ Abdul Kalam from web world?', additional_kwargs={}, response_metadata={}), SystemMessage(content='web', additional_kwargs={}, response_metadata={}), SystemMessage(content='Dr. Avul Pakir Jainulabdeen (APJ) Abdul Kalam, fondly known as the "Missile Man of India," was one of India\'s most esteemed scientists and statesmen. Born on October 15, 1931, in Rameswaram, Tamil Nadu, Kalam came from a humble background. A.P.J. Abdul Kalam, the esteemed scientist and former president of India, left an enduring legacy through his contributions to space research and inspired millions with his vision for a prosperous country. A grand tribute to one of India\'s most loved and respected figures is officially in the making. At the 78th Cannes Film Festival, the makers of Kalam: The Missile Man of India announced a biopic based on the life of Bharat Ratna Dr APJ Abdul Kalam. Known for his incredible contributions to India\'s space and missile programmes, and his time as the 11th President of India, Dr Kalam is a ... APJ Abdul Kalam Death Anniversary: Fondly called India\'s \'Missile man\', Dr Kalam was particularly close to young people and he loved to be among students. The great passion for science that drove Dr. APJ Abdul Kalam\'s innovative efforts in missile and aerospace technologies gained him the moniker "Missile Man of India." His commitment to scientific advancement till now inspires great number of young people to seek jobs in science and technology.', additional_kwargs={}, response_metadata={})], 'validation_passed': False, 'last_route': 'web', 'retry_count': 0}
[ValidationNode.validation_router]: validation_passed=True, retry_count=0
{'validation_router': {'messages': [SystemMessage(content='Tell me latest information about Dr. APJ Abdul Kalam from web world?', additional_kwargs={}, response_metadata={}), SystemMessage(content='web', additional_kwargs={}, response_metadata={}), SystemMessage(content='Dr. Avul Pakir Jainulabdeen (APJ) Abdul Kalam, fondly known as the "Missile Man of India," was one of India\'s most esteemed scientists and statesmen. Born on October 15, 1931, in Rameswaram, Tamil Nadu, Kalam came from a humble background. A.P.J. Abdul Kalam, the esteemed scientist and former president of India, left an enduring legacy through his contributions to space research and inspired millions with his vision for a prosperous country. A grand tribute to one of India\'s most loved and respected figures is officially in the making. At the 78th Cannes Film Festival, the makers of Kalam: The Missile Man of India announced a biopic based on the life of Bharat Ratna Dr APJ Abdul Kalam. Known for his incredible contributions to India\'s space and missile programmes, and his time as the 11th President of India, Dr Kalam is a ... APJ Abdul Kalam Death Anniversary: Fondly called India\'s \'Missile man\', Dr Kalam was particularly close to young people and he loved to be among students. The great passion for science that drove Dr. APJ Abdul Kalam\'s innovative efforts in missile and aerospace technologies gained him the moniker "Missile Man of India." His commitment to scientific advancement till now inspires great number of young people to seek jobs in science and technology.', additional_kwargs={}, response_metadata={})], 'validation_passed': True, 'last_route': 'web', 'retry_count': 0}}


[SupervisorNode.classify_request]:START: {'messages': [SystemMessage(content='Do you think India will be able to develop there own LLM? Agentic AI is fascinating!', additional_kwargs={}, response_metadata={})], 'last_route': '', 'retry_count': 0}
[SupervisorNode.classify_request]:END: {'messages': [SystemMessage(content='llm', additional_kwargs={}, response_metadata={})], 'validation_passed': '', 'last_route': 'llm', 'retry_count': 0}
[SupervisorNode.get_route]:START: {'messages': [SystemMessage(content='Do you think India will be able to develop there own LLM? Agentic AI is fascinating!', additional_kwargs={}, response_metadata={}), SystemMessage(content='llm', additional_kwargs={}, response_metadata={})], 'validation_passed': '', 'last_route': 'llm', 'retry_count': 0}
next_node: llm
[SupervisorNode.get_route]:END: {'messages': [SystemMessage(content='Do you think India will be able to develop there own LLM? Agentic AI is fascinating!', additional_kwargs={}, response_metadata={}), SystemMessage(content='llm', additional_kwargs={}, response_metadata={})], 'validation_passed': '', 'last_route': 'llm', 'retry_count': 0}
{'supervisor': {'messages': [SystemMessage(content='llm', additional_kwargs={}, response_metadata={})], 'validation_passed': '', 'last_route': 'llm', 'retry_count': 0}}
[LLMNode.llm_response]:START: {'messages': [SystemMessage(content='Do you think India will be able to develop there own LLM? Agentic AI is fascinating!', additional_kwargs={}, response_metadata={}), SystemMessage(content='llm', additional_kwargs={}, response_metadata={})], 'validation_passed': '', 'last_route': 'llm', 'retry_count': 0}
[LLMNode.llm_response]:END: {'messages': [SystemMessage(content="India has a strong potential to develop its own LLMs.  Several factors contribute to this:\n\n* **Strong IT sector:** India boasts a large and rapidly growing IT sector with a significant pool of skilled engineers and researchers.  This provides the necessary human capital for LLM development.\n* **Growing computational resources:**  Access to computational resources, while still potentially a bottleneck compared to the US or China, is increasing in India. Cloud computing infrastructure is expanding, and there's a growing investment in high-performance computing.\n* **Government support:** The Indian government has shown increasing interest in AI and is likely to provide funding and policy support for LLM development.  Initiatives focused on digitalization and technological advancement create a favorable environment.\n* **Large multilingual dataset:**  India's linguistic diversity presents both a challenge and an opportunity.  Developing LLMs that can handle multiple Indian languages is a significant undertaking but also a potential source of competitive advantage.  This could lead to innovations in multilingual AI.\n* **Existing research institutions:**  Several Indian universities and research institutions are actively involved in AI research, laying the groundwork for LLM development.\n\nHowever, challenges remain:\n\n* **Data scarcity:** While India has a large population, obtaining high-quality, curated datasets for training LLMs can be difficult.  Data biases and inconsistencies need careful attention.\n* **Infrastructure limitations:**  Compared to global giants, access to cutting-edge hardware and infrastructure remains a constraint.\n* **Talent competition:**  Attracting and retaining top AI talent can be challenging, as global companies compete for the best minds.\n\n\nIn summary, India's ability to develop its own LLMs is very real, but success will depend on overcoming these challenges.  It's likely to be a gradual process, with initial models possibly focusing on specific applications or languages before scaling to more general-purpose LLMs.  The development of agentic AI, a more advanced aspect, will follow further down the line, dependent on progress in foundational LLM capabilities.  The potential is there, but significant investment and strategic planning will be crucial.", additional_kwargs={}, response_metadata={})], 'validation_passed': '', 'last_route': 'llm', 'retry_count': 0}
{'llm': {'messages': [SystemMessage(content="India has a strong potential to develop its own LLMs.  Several factors contribute to this:\n\n* **Strong IT sector:** India boasts a large and rapidly growing IT sector with a significant pool of skilled engineers and researchers.  This provides the necessary human capital for LLM development.\n* **Growing computational resources:**  Access to computational resources, while still potentially a bottleneck compared to the US or China, is increasing in India. Cloud computing infrastructure is expanding, and there's a growing investment in high-performance computing.\n* **Government support:** The Indian government has shown increasing interest in AI and is likely to provide funding and policy support for LLM development.  Initiatives focused on digitalization and technological advancement create a favorable environment.\n* **Large multilingual dataset:**  India's linguistic diversity presents both a challenge and an opportunity.  Developing LLMs that can handle multiple Indian languages is a significant undertaking but also a potential source of competitive advantage.  This could lead to innovations in multilingual AI.\n* **Existing research institutions:**  Several Indian universities and research institutions are actively involved in AI research, laying the groundwork for LLM development.\n\nHowever, challenges remain:\n\n* **Data scarcity:** While India has a large population, obtaining high-quality, curated datasets for training LLMs can be difficult.  Data biases and inconsistencies need careful attention.\n* **Infrastructure limitations:**  Compared to global giants, access to cutting-edge hardware and infrastructure remains a constraint.\n* **Talent competition:**  Attracting and retaining top AI talent can be challenging, as global companies compete for the best minds.\n\n\nIn summary, India's ability to develop its own LLMs is very real, but success will depend on overcoming these challenges.  It's likely to be a gradual process, with initial models possibly focusing on specific applications or languages before scaling to more general-purpose LLMs.  The development of agentic AI, a more advanced aspect, will follow further down the line, dependent on progress in foundational LLM capabilities.  The potential is there, but significant investment and strategic planning will be crucial.", additional_kwargs={}, response_metadata={})], 'validation_passed': '', 'last_route': 'llm', 'retry_count': 0}}
[ValidationNode.validation_router]: START: {'messages': [SystemMessage(content='Do you think India will be able to develop there own LLM? Agentic AI is fascinating!', additional_kwargs={}, response_metadata={}), SystemMessage(content='llm', additional_kwargs={}, response_metadata={}), SystemMessage(content="India has a strong potential to develop its own LLMs.  Several factors contribute to this:\n\n* **Strong IT sector:** India boasts a large and rapidly growing IT sector with a significant pool of skilled engineers and researchers.  This provides the necessary human capital for LLM development.\n* **Growing computational resources:**  Access to computational resources, while still potentially a bottleneck compared to the US or China, is increasing in India. Cloud computing infrastructure is expanding, and there's a growing investment in high-performance computing.\n* **Government support:** The Indian government has shown increasing interest in AI and is likely to provide funding and policy support for LLM development.  Initiatives focused on digitalization and technological advancement create a favorable environment.\n* **Large multilingual dataset:**  India's linguistic diversity presents both a challenge and an opportunity.  Developing LLMs that can handle multiple Indian languages is a significant undertaking but also a potential source of competitive advantage.  This could lead to innovations in multilingual AI.\n* **Existing research institutions:**  Several Indian universities and research institutions are actively involved in AI research, laying the groundwork for LLM development.\n\nHowever, challenges remain:\n\n* **Data scarcity:** While India has a large population, obtaining high-quality, curated datasets for training LLMs can be difficult.  Data biases and inconsistencies need careful attention.\n* **Infrastructure limitations:**  Compared to global giants, access to cutting-edge hardware and infrastructure remains a constraint.\n* **Talent competition:**  Attracting and retaining top AI talent can be challenging, as global companies compete for the best minds.\n\n\nIn summary, India's ability to develop its own LLMs is very real, but success will depend on overcoming these challenges.  It's likely to be a gradual process, with initial models possibly focusing on specific applications or languages before scaling to more general-purpose LLMs.  The development of agentic AI, a more advanced aspect, will follow further down the line, dependent on progress in foundational LLM capabilities.  The potential is there, but significant investment and strategic planning will be crucial.", additional_kwargs={}, response_metadata={})], 'validation_passed': '', 'last_route': 'llm', 'retry_count': 0}
[ValidationNode.validation_router]: validation_passed=True, retry_count=0
{'validation_router': {'messages': [SystemMessage(content='Do you think India will be able to develop there own LLM? Agentic AI is fascinating!', additional_kwargs={}, response_metadata={}), SystemMessage(content='llm', additional_kwargs={}, response_metadata={}), SystemMessage(content="India has a strong potential to develop its own LLMs.  Several factors contribute to this:\n\n* **Strong IT sector:** India boasts a large and rapidly growing IT sector with a significant pool of skilled engineers and researchers.  This provides the necessary human capital for LLM development.\n* **Growing computational resources:**  Access to computational resources, while still potentially a bottleneck compared to the US or China, is increasing in India. Cloud computing infrastructure is expanding, and there's a growing investment in high-performance computing.\n* **Government support:** The Indian government has shown increasing interest in AI and is likely to provide funding and policy support for LLM development.  Initiatives focused on digitalization and technological advancement create a favorable environment.\n* **Large multilingual dataset:**  India's linguistic diversity presents both a challenge and an opportunity.  Developing LLMs that can handle multiple Indian languages is a significant undertaking but also a potential source of competitive advantage.  This could lead to innovations in multilingual AI.\n* **Existing research institutions:**  Several Indian universities and research institutions are actively involved in AI research, laying the groundwork for LLM development.\n\nHowever, challenges remain:\n\n* **Data scarcity:** While India has a large population, obtaining high-quality, curated datasets for training LLMs can be difficult.  Data biases and inconsistencies need careful attention.\n* **Infrastructure limitations:**  Compared to global giants, access to cutting-edge hardware and infrastructure remains a constraint.\n* **Talent competition:**  Attracting and retaining top AI talent can be challenging, as global companies compete for the best minds.\n\n\nIn summary, India's ability to develop its own LLMs is very real, but success will depend on overcoming these challenges.  It's likely to be a gradual process, with initial models possibly focusing on specific applications or languages before scaling to more general-purpose LLMs.  The development of agentic AI, a more advanced aspect, will follow further down the line, dependent on progress in foundational LLM capabilities.  The potential is there, but significant investment and strategic planning will be crucial.", additional_kwargs={}, response_metadata={})], 'validation_passed': True, 'last_route': 'llm', 'retry_count': 0}}

Process finished with exit code 0

"""